/**
 * The scorecard, as a print-clean PDF.
 *
 * BRIEF.md §6: "Ship the blank scorecard as HTML, as a print-clean PDF, and as the
 * markdown. Ungated. Stable filenames carrying the methodology version. The PDF is
 * generated in the build, not exported by hand, and is checked."
 *
 * Generated by rendering the built site's own /scorecard/ route, so the PDF cannot
 * drift from the page: there is one scorecard, and this is a second way of reading it.
 * `preferCSSPageSize` hands page size and margins to the `@page` rule in styles.css
 * rather than restating them here — the print stylesheet stays the one source.
 *
 * Run after eleventy, as part of `npm run build`. Playwright is already a pinned
 * dependency for the check suite; this adds no new one.
 */

import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { serve } from '../tests/lib/harness.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, '_site');

const oal = JSON.parse(readFileSync(path.join(ROOT, 'src/_data/oal.json'), 'utf8'));
const filename = `ordoia-scorecard-audit-oal-v${oal.current}.pdf`;
const target = path.join(OUT, 'scorecard', filename);

const site = await serve(OUT);
const browser = await chromium.launch();
const page = await browser.newPage();

const response = await page.goto(site.origin + '/scorecard/', { waitUntil: 'networkidle' });
if (!response?.ok()) {
  throw new Error('cannot render /scorecard/ — build the site before generating its PDF');
}
await page.evaluate(() => document.fonts.ready);

const pdf = await page.pdf({ preferCSSPageSize: true, printBackground: true });
writeFileSync(target, pdf);

await browser.close();
await site.close();

// Report, rather than assert quietly. Check 11 asserts the same properties against
// the artifact on every run; this is what the person running the build sees.
const text = pdf.toString('latin1');
const pages = [...text.matchAll(/\/Type\s*\/Page[^s]/g)].length;
const header = pdf.subarray(0, 5).toString('latin1');

if (header !== '%PDF-') throw new Error(`output is not a PDF (header "${header}")`);
if (pages < 1) throw new Error('the PDF reports no pages');

console.log(
  `[pdf] scorecard/${filename} — ${pdf.length.toLocaleString()} bytes, ${pages} page${pages === 1 ? '' : 's'}, A4 from the print stylesheet`
);
